- apps/web-api/src/account/account.dto.ts
- apps/web-api/src/account/account.service.ts
- apps/web-api/src/holder/holder.resolver.ts
- apps/web-api/src/holder/holder.service.ts
- apps/web-api/src/transfer/transfer.resolver.ts
- apps/web-api/src/transfer/transfer.service.ts
> add count to all modules

- apps/web-api/src/account/account.resolver.ts
- apps/web-api/src/collection/collection.resolver.ts
- apps/web-api/src/collection/collection.service.ts
- apps/web-api/src/event/event.resolver.ts
- apps/web-api/src/extrinsic/extrinsic.resolver.ts
- apps/web-api/src/holder/holder.resolver.ts
- apps/web-api/src/tokens/token.resolver.ts
- apps/web-api/src/transfer/transfer.resolver.ts
- apps/web-api/src/utils/base.service.ts
- apps/web-api/src/utils/gql-query-args.ts
- package.json
-handle _or operator
-_and params: array
> _or operator

- apps/web-api/src/block/block.types.ts
- apps/web-api/src/extrinsic/extrinsic.resolver.ts
> minor fixes

- apps/web-api/src/utils/base.service.ts
-add collection alias to order by condition
> ambiguous error fix

- apps/web-api/src/account/account.resolver.ts
- apps/web-api/src/account/account.service.ts
- apps/web-api/src/block/block.types.ts
- apps/web-api/src/event/event.resolver.ts
- apps/web-api/src/event/event.service.ts
- apps/web-api/src/extrinsic/extrinsic.resolver.ts
- apps/web-api/src/extrinsic/extrinsic.service.ts
- apps/web-api/src/holder/holder.resolver.ts
- apps/web-api/src/tokens/token.resolver.ts
- apps/web-api/src/transfer/transfer.resolver.ts
- apps/web-api/src/transfer/transfer.service.ts
- apps/web-api/src/utils/base.service.ts
> fix Extrinsic query

- apps/web-api/src/collection/collection.dto.ts
- common/entities/Collections.ts
> Updated collections.owner_can_* columns

- apps/web-api/src/collection/collection.service.ts
- apps/web-api/src/tokens/token.service.ts
> collection_cover value calculation rework

- apps/web-api/src/collection/collection.dto.ts
- apps/web-api/src/collection/collection.service.ts
- common/entities/Collections.ts
-collection entity add collection_cover
-fix collection.service: applyTokensSubQuery method if where is empty
> fix token_limit type

- apps/web-api/src/collection/collection.resolver.types.ts
- apps/web-api/src/collection/collection.service.ts
- apps/web-api/src/utils/base.service.ts
- apps/web-api/src/utils/base.service.types.ts
- apps/web-api/test/collection.e2e-spec.ts
-filter collections by tokens query result
> fix collections service

- apps/web-api/src/tokens/token.dto.ts
- apps/web-api/src/tokens/token.resolver.types.ts
- apps/web-api/src/tokens/token.service.ts
- apps/web-api/test/fixtures/tokens.yml
- apps/web-api/test/tokens.e2e-spec.ts
- common/entities/Tokens.ts
- package-lock.json
> tokens.parent_id

- apps/crawler/src/processors/collections-processor.ts
- apps/crawler/src/processors/tokens-processor.ts
Closes [SCAN-271](https://cryptousetech.atlassian.net/browse/SCAN-271)
> Tokens and collection deletion

- apps/web-api/src/tokens/token.dto.ts
- apps/web-api/src/tokens/token.resolver.types.ts
- apps/web-api/src/tokens/token.service.ts
> fix tokens query builder

- apps/crawler/src/subscribers/accounts-subscriber.service.ts
- apps/web-api/src/account/account.service.ts
- common/entities/Account.ts
- migrations/1659954827364-remove-account-balance-field.ts
> Remove balances field from account

- apps/crawler/src/processor.config.service.ts
- apps/crawler/src/subscribers/processor.service.ts
- common/constants.ts
> Dynamic status schema name

- apps/web-api/src/tokens/token.dto.ts
- apps/web-api/src/tokens/token.resolver.types.ts
- apps/web-api/src/tokens/token.service.ts
- apps/web-api/src/utils/base.service.spec.ts
- apps/web-api/src/utils/base.service.ts
> tokens where

- apps/web-api/src/transaction/transaction.resolver.types.ts
- apps/web-api/src/transaction/transaction.service.ts
> resolver args

- migrations/1659610454950-total-stats-triggers-fix.ts
- migrations/1661761544305-accounts-triggers-fix.ts
> minot fixes

- apps/crawler/src/writers/collection.writer.service.ts
- apps/web-api/src/collection/collection.dto.ts
- apps/web-api/src/collection/collection.resolver.types.ts
- apps/web-api/src/collection/collection.service.ts
- common/entities/Collections.ts
- migrations/1663662447623-collections-permissions.ts
> Collection permissions fields

- apps/web-api/src/tokens/token.resolver.types.ts
- apps/web-api/src/tokens/token.service.ts
> tokens order

- apps/web-api/src/event/event.service.ts
- apps/web-api/src/event/token-event.resolver.ts
- apps/web-api/src/event/token-event.service.ts
> Fix for token_events resolver

- apps/crawler/src/services/token/nesting.service.ts
- apps/crawler/src/services/token/token.service.ts
> Remove token from parents if it was burned

- migrations/1670928745000-triggers-new-structure-fix.ts
- migrations/1670929199000-collection-stats-triggers-fix.ts
Change event CollectionOwnedChanged > CollectionOwnerChanged.  Update migration collection-stats-triggers and trigger structure
> fix: Change event CollectionOwnedChanged > CollectionOwnerChanged. 

- apps/web-api/src/app.module.ts
- apps/web-api/src/circulating/circulating-supply.controller.ts
- apps/web-api/src/circulating/circulating-supply.service.ts
- apps/web-api/src/circulating/circulating.module.ts
- common/cache/cache-provider.module.ts
- common/config/cache.config.ts
- common/config/config.module.ts
- common/config/sentry.config.ts
- common/config/subscribers.config.ts
- common/constants.ts
- common/sdk/sdk-cache.decorator.ts
- common/sdk/sdk-factory.ts
- common/sdk/sdk.module.ts
- common/sdk/sdk.service.ts
- package-lock.json
- package.json
Outputting data from the scan circulating supply and total supply from the chain. [SDK-826]
> Added endpoint get/circulating-supply.
